### ISSUE TITLE
Fail for following coordinates

### ISSUE THREAD

**Issue by Narzew** [zbycz/srtm-hgt-reader#1]
Welcome, the program failed for following coordinates:
    50.83341 15.68387 - OK
    50.83085 15.6852 - OK
    -16.196715 -67.751205 - CRASH
    -16.342148 -68.038287
    -15.65158 -71.60931
First two coordinates was parsed OK, but the program crashed at third coordinate. I have all correct .hgt files located in srtm/ folder.
    Opening srtm/N50E015.hgt
    Opening srtm/S16W067.hgt [Crash]
I have double checked, I have both the files in srtm/ folder. Additionally, I have re-downloaded second file and the problem remains.

**Comment by zbycz** [comment]
Oh yeah, I think there is not support for negative coordinates. Please look
in the source code, you should only need to add one of clause.

**Comment by Narzew** [comment]
I tried to do something like this: https://pastebin.com/KbDXmg6z
But the program now returns bad coordinates :/ I got 4500 instead of 3600 in one point, what I did wrong here?

**Comment by zbycz** [comment]
In case anybody needs, this is the @Narzew's solution:

> Hi, I have fixed the bug 😉 https://github.com/Narzew/srtm-hgt-reader/blob/master/srtmHgtReader.cpp, lines 110-115; I have just changed (int)latDec = (int)lat; to (int)latDec = (int)floor(lat); The same with lonDec. Now code works for any coordinate 😉
